// AUTO-GENERATED by scripts/fetch-decor.mjs — do not edit by hand.
// CC0 decor models sourced from poly.pizza. All are public-domain (CC0); the
// credits below are a courtesy and are intentionally NOT rendered on the
// frontend. Re-run the script to refresh.
export interface DecorCredit {
  slug: string;
  file: string;
  glb: string | null;
  title: string | null;
  creator: string | null;
  license: string | null;
  source: string;
}
export const DECOR_CREDITS: DecorCredit[] = [
  {
    "slug": "monstera",
    "file": "/models/monstera.glb",
    "glb": "https://static.poly.pizza/6c95757c-6420-4408-9a42-633b951ec675.glb",
    "title": "Monstera Plant",
    "creator": "Isa Lousberg",
    "license": "CC0",
    "source": "https://poly.pizza/m/pkmHvN1O2V"
  },
  {
    "slug": "monstera-large",
    "file": "/models/monstera-large.glb",
    "glb": "https://static.poly.pizza/9752cda7-f248-4b5e-acf6-a58527861239.glb",
    "title": "Large Monstera Plant",
    "creator": "Isa Lousberg",
    "license": "CC0",
    "source": "https://poly.pizza/m/kZQ2WmnJFI"
  },
  {
    "slug": "snake-plant",
    "file": "/models/snake-plant.glb",
    "glb": "https://static.poly.pizza/f972935d-4083-474a-aa51-af7ceec71797.glb",
    "title": "Sansevieria Plant",
    "creator": "Isa Lousberg",
    "license": "CC0",
    "source": "https://poly.pizza/m/BDwimVUool"
  },
  {
    "slug": "houseplant",
    "file": "/models/houseplant.glb",
    "glb": "https://static.poly.pizza/1683c0b1-4dd9-4d45-910e-cf3e46f163f5.glb",
    "title": "Houseplant",
    "creator": "Quaternius",
    "license": "CC0",
    "source": "https://poly.pizza/m/bfLOqIV5uP"
  },
  {
    "slug": "fern",
    "file": "/models/fern.glb",
    "glb": "https://static.poly.pizza/f94d836f-4eb4-4db0-aa53-3ecdddffa527.glb",
    "title": "Fern",
    "creator": "Quaternius",
    "license": "CC0",
    "source": "https://poly.pizza/m/jqcanvH7D6"
  },
  {
    "slug": "horse-statue",
    "file": "/models/horse-statue.glb",
    "glb": "https://static.poly.pizza/55b0aa03-543c-439d-a7d7-f0ac4c23578f.glb",
    "title": "Horse Statue",
    "creator": "Quaternius",
    "license": "CC0",
    "source": "https://poly.pizza/m/AK9CmjFnL6"
  },
  {
    "slug": "stag-statue",
    "file": "/models/stag-statue.glb",
    "glb": "https://static.poly.pizza/a44b71cc-0a88-4fa6-a89e-833f46fd19c2.glb",
    "title": "Stag Statue",
    "creator": "Quaternius",
    "license": "CC0",
    "source": "https://poly.pizza/m/cKloIsNcT8"
  },
  {
    "slug": "pedestal",
    "file": "/models/pedestal.glb",
    "glb": "https://static.poly.pizza/cc5afa7b-86ed-44d0-9521-709ade03fda3.glb",
    "title": "Pedestal",
    "creator": "Quaternius",
    "license": "CC0",
    "source": "https://poly.pizza/m/wUeoDKnFBF"
  },
  {
    "slug": "column",
    "file": "/models/column.glb",
    "glb": "https://static.poly.pizza/105dfd4b-6af3-4732-8c29-a89b15135b07.glb",
    "title": "Column Round",
    "creator": "Quaternius",
    "license": "CC0",
    "source": "https://poly.pizza/m/n8ZvVFcJhl"
  }
];
