// One-off: download the curated set of CC0 decor models from poly.pizza into
// public/models/, and emit src/lib/decor-credits.ts (in-code attribution only;
// never shown on the frontend). All models are CC0 — attribution is courtesy.
//
// Usage: node scripts/fetch-decor.mjs

import { mkdir, writeFile } from "node:fs/promises";
import { createWriteStream } from "node:fs";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";

// Curated CC0 picks (slug → poly.pizza id). Verified license=CC0 via discovery.
const PICKS = [
  { slug: "monstera", id: "pkmHvN1O2V" },
  { slug: "monstera-large", id: "kZQ2WmnJFI" },
  { slug: "snake-plant", id: "BDwimVUool" },
  { slug: "houseplant", id: "bfLOqIV5uP" },
  { slug: "fern", id: "jqcanvH7D6" },
  { slug: "palm", id: "A6cKJYFsIb" },
  { slug: "tree", id: "i4QMw4L64D" },
  { slug: "horse-statue", id: "AK9CmjFnL6" },
  { slug: "stag-statue", id: "cKloIsNcT8" },
];

const pick = (re, html) => {
  const m = html.match(re);
  return m ? m[1] : null;
};

async function meta(id) {
  const res = await fetch(`https://poly.pizza/m/${id}`, { headers: { "user-agent": "Mozilla/5.0" } });
  const html = await res.text();
  return {
    glb: pick(/(https:\/\/static\.poly\.pizza\/[a-f0-9-]+\.glb)\b/, html),
    title: pick(/property="og:title" content="([^"]*?)(?: - Free Model[^"]*)?"/, html),
    creator: pick(/"Creator":\{"Username":"([^"]*)"/, html),
    license: pick(/\b(CC0|CC-BY(?:-SA)? ?[0-9.]*)\b/, html),
  };
}

await mkdir("public/models", { recursive: true });
const credits = [];
for (const p of PICKS) {
  const m = await meta(p.id);
  if (!m.glb) {
    console.error(`! no glb for ${p.slug} (${p.id})`);
    continue;
  }
  const res = await fetch(m.glb);
  await pipeline(Readable.fromWeb(res.body), createWriteStream(`public/models/${p.slug}.glb`));
  const bytes = Number(res.headers.get("content-length")) || 0;
  console.log(`✓ ${p.slug.padEnd(16)} ${(bytes / 1024).toFixed(0).padStart(5)}KB  ${m.title} — ${m.creator} (${m.license})`);
  credits.push({ slug: p.slug, file: `/models/${p.slug}.glb`, ...m, source: `https://poly.pizza/m/${p.id}` });
}

const ts = `// AUTO-GENERATED by scripts/fetch-decor.mjs — do not edit by hand.
// CC0 decor models sourced from poly.pizza. All are public-domain (CC0); the
// credits below are a courtesy and are intentionally NOT rendered on the
// frontend. Re-run the script to refresh.
export interface DecorCredit {
  slug: string;
  file: string;
  glb: string | null;
  title: string | null;
  creator: string | null;
  license: string | null;
  source: string;
}
export const DECOR_CREDITS: DecorCredit[] = ${JSON.stringify(credits, null, 2)};
`;
await writeFile("src/lib/decor-credits.ts", ts);
console.log(`\nWrote src/lib/decor-credits.ts (${credits.length} models)`);
